# Using Numpy

In [1]:
import numpy as np

In [2]:
# create 2-d array
arr_2d = np.array([[1,3,4],
                 [3,6,7]], dtype = float)

print(arr_2d)

[[1. 3. 4.]
 [3. 6. 7.]]


In [3]:
arr_2d.shape

(2, 3)

In [4]:
# create ones list
ones_arr = np.ones(5) # by default float is set if not menstioned otherwise

print(ones_arr)

[1. 1. 1. 1. 1.]


In [5]:
ones_arr1 = np.ones((3,4), dtype = "int")

print(ones_arr1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [6]:
# create empty list
empty_arr = np.empty((3,4))

print(empty_arr)

[[0.00000000e+000 1.00937611e-320 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.31370903e-076 4.71195450e-090 1.42648537e-071]
 [5.51234099e+169 8.93194100e+165 3.99910963e+252 1.46030983e-319]]


In [7]:
zero = np.zeros(5)

print(zero)

[0. 0. 0. 0. 0.]


In [8]:
zero_nd = np.zeros((3,4))

print(zero_nd)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
zero_nd = zero_nd.reshape((2,6))
print(zero_nd)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
# creating a new list in range using numpy

arange_arr = np.arange(1,11)

print(arange_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
# get fixed value in range using linspace function
# syntax of linespace function: 
linspace_arr = np.linspace(1,5,4)

print(linspace_arr)

[1.         2.33333333 3.66666667 5.        ]


In [21]:
# coverting 1-d to 2-d array
arr1 = np.arange(1,11)
print(arr1)

arr2 = arr1.reshape(2,5)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
# reval

In [23]:
# flatten

In [26]:
# rows into colums
trans_arr = arr1.transpose()

print(trans_arr)

[ 1  2  3  4  5  6  7  8  9 10]
